import {
  BarnSvg,
  BeachSvg,
  CactusSvg,
  CastleSvg,
  CaveEntranceSvg,
  DiamondSvg,
  FishingBoatSvg,
  ForestCampSvg,
  IslandSvg,
  MountainSvg,
  PoolSvg,
  SkingSvg,
  SnowSvg,
  VillaSvg,
  WindmillSvg,
} from "@/components/svg";

export const categoryMap = {
  TbBeach: BeachSvg,
  TbMountain: MountainSvg,
  GiWindmill: WindmillSvg,
  IoDiamond: DiamondSvg,
  GiBarn: BarnSvg,
  GiCactus: CactusSvg,
  BsSnow: SnowSvg,
  GiForestCamp: ForestCampSvg,
  GiCaveEntrance: CaveEntranceSvg,
  GiCastle: CastleSvg,
  FaSkiing: SkingSvg,
  GiBoatFishing: FishingBoatSvg,
  GiIsland: IslandSvg,
  TbPool: PoolSvg,
  MdOutlineVilla: VillaSvg,
};
