import "./globals.css";
import { ReactNode } from "react";
import { Nunito } from "next/font/google";
import { getLogedInUser } from "@/utils/getLogedInUser";
import {
  CategoryList,
  ClientOnley,
  Header,
  ListingForm,
  Logister,
} from "@/components";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const logedInUser = await getLogedInUser();

  return (
    <html lang="en">
      <body className={`${nunito.variable} font-nunito`}>
        <Header user={logedInUser} />
        <ClientOnley>
          <ListingForm />
          <Logister formVals={{ email: "", password: "", username: "" }} />
        </ClientOnley>
        {/* @ts-expect-error Async Server Component  */}
        <CategoryList />
        {children}
      </body>
    </html>
  );
}
